-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 23, 2019 at 03:19 AM
-- Server version: 10.4.6-MariaDB
-- PHP Version: 7.3.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `berita_bps`
--

-- --------------------------------------------------------

--
-- Table structure for table `berita`
--

CREATE TABLE `berita` (
  `header` varchar(255) NOT NULL,
  `ringkasan` text NOT NULL,
  `sumber` varchar(255) NOT NULL,
  `tanggal` date NOT NULL,
  `link` text NOT NULL,
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `berita`
--

INSERT INTO `berita` (`header`, `ringkasan`, `sumber`, `tanggal`, `link`, `id`) VALUES
('Ekonomi Sultra Tumbuh 6,18 Persen di Triwulan III 2019', 'ZONASULTRA.COM, KENDARI  Badan Pusat Statistik (BPS) Provinsi Sulawesi Tenggara (Sultra) menyebutkan pertumbuhan ekonomi Sultra pada triwulan III ...', 'ZonaSultra.com', '2019-11-07', 'http://news.google.com/articles/CBMiUWh0dHBzOi8vem9uYXN1bHRyYS5jb20vZWtvbm9taS1zdWx0cmEtdHVtYnVoLTYxOC1wZXJzZW4tZGktdHJpd3VsYW4taWlpLTIwMTkuaHRtbNIBAA?hl=id&gl=ID&ceid=ID%3Aid', 1),
('Kepala BPS: Independensi Harga Mati  Nasional Terkini', 'Terkini.com  Kepala Badan Pusat Statistik (BPS) Suhariyanto mengatakan, independensi merupakan landasan bagi pihaknya untuk menyajikan data utuh ...', 'Terkini.com', '2019-11-07', 'http://news.google.com/articles/CBMiSGh0dHBzOi8vdGVya2luaS5jb20va2VwYWxhLWJwcy1pbmRlcGVuZGVuc2ktaGFyZ2EtbWF0aS1uYXNpb25hbC10ZXJraW5pL9IBTGh0dHBzOi8vdGVya2luaS5jb20va2VwYWxhLWJwcy1pbmRlcGVuZGVuc2ktaGFyZ2EtbWF0aS1uYXNpb25hbC10ZXJraW5pL2FtcC8?hl=id&gl=ID&ceid=ID%3Aid', 2),
('Triwulan III-2019 Ekonomi Kaltim Tumbuh 1,48 Persen', 'SAMARINDA.NIAGA.ASIA-Ekonomi Kalimantan Timur (Kaltim) Triwulan III-2019 dibanding Triwulan II-2019 tumbuh sebesar 1,48 persen (q-to-q = quarter to ...', 'Niaga Asia', '2019-11-07', 'http://news.google.com/articles/CBMiSmh0dHBzOi8vd3d3Lm5pYWdhLmFzaWEvdHJpd3VsYW4taWlpLTIwMTktZWtvbm9taS1rYWx0aW0tdHVtYnVoLTE0OC1wZXJzZW4v0gEA?hl=id&gl=ID&ceid=ID%3Aid', 3),
('Industri Manufaktur Besar dan Sedang di Sulsel Tumbuh 4,85 persen', 'Lanjut Yos, untuk pertumbuhan produksi industri manufaktur mikro dan kecil pada triwulan III mengalami kenaikan sebesar 7,11 persen dibandingkan.', 'Tribun Timur', '2019-11-07', 'http://news.google.com/articles/CBMia2h0dHBzOi8vbWFrYXNzYXIudHJpYnVubmV3cy5jb20vMjAxOS8xMS8wNy9pbmR1c3RyaS1tYW51ZmFrdHVyLWJlc2FyLWRhbi1zZWRhbmctZGktc3Vsc2VsLXR1bWJ1aC00ODUtcGVyc2Vu0gFvaHR0cHM6Ly9tYWthc3Nhci50cmlidW5uZXdzLmNvbS9hbXAvMjAxOS8xMS8wNy9pbmR1c3RyaS1tYW51ZmFrdHVyLWJlc2FyLWRhbi1zZWRhbmctZGktc3Vsc2VsLXR1bWJ1aC00ODUtcGVyc2Vu?hl=id&gl=ID&ceid=ID%3Aid', 4),
('Mulai Tahun Depan, BPS Tak Lagi Merilis Indeks Tendensi Bisnis  merdeka.com', 'Suhariyanto mengatakan, selama ini indeks tendensi bisnis tidak terlalu besar mendapat perhatian Sebab beberapa lembaga lain seperti Bank Indonesia juga ...', 'merdeka.com', '2019-11-07', 'http://news.google.com/articles/CBMiXWh0dHBzOi8vbS5tZXJkZWthLmNvbS91YW5nL211bGFpLXRhaHVuLWRlcGFuLWJwcy10YWstbGFnaS1tZXJpbGlzLWluZGVrcy10ZW5kZW5zaS1iaXNuaXMuaHRtbNIBYWh0dHBzOi8vbS5tZXJkZWthLmNvbS9hbXAvdWFuZy9tdWxhaS10YWh1bi1kZXBhbi1icHMtdGFrLWxhZ2ktbWVyaWxpcy1pbmRla3MtdGVuZGVuc2ktYmlzbmlzLmh0bWw?hl=id&gl=ID&ceid=ID%3Aid', 5),
('Jaga Pertumbuhan Ekonomi 2019 di 5 Persen, Pemerintah Diminta Lakukan ini  merdeka.com', 'Tahun 2019 akan berakhir dalam 2 bulan. Namun, pertumbuhan ekonomi Indonesia terus melambat sejak kuartal I. Data terbaru Badan Pusat Statistik (BPS) ...', 'merdeka.com', '2019-11-07', 'http://news.google.com/articles/CBMiamh0dHBzOi8vd3d3Lm1lcmRla2EuY29tL3VhbmcvamFnYS1wZXJ0dW1idWhhbi1la29ub21pLTIwMTktZGktNS1wZXJzZW4tcGVtZXJpbnRhaC1kaW1pbnRhLWxha3VrYW4taW5pLmh0bWzSAWxodHRwczovL20ubWVyZGVrYS5jb20vYW1wL3VhbmcvamFnYS1wZXJ0dW1idWhhbi1la29ub21pLTIwMTktZGktNS1wZXJzZW4tcGVtZXJpbnRhaC1kaW1pbnRhLWxha3VrYW4taW5pLmh0bWw?hl=id&gl=ID&ceid=ID%3Aid', 6),
('Ekonomi  Netflix dan Iflix Sumbang Perlambatan Ekonomi RI Triwulan III 2019', 'AKURAT.CO, Badan Pusat Statistik (BPS) telah merilis angka pertumbuhan ekonomi pada triwulan III 2019 hanya sebesar 5,02 persen. Realisasi itu mengalami ...', 'akurat', '2019-11-07', 'http://news.google.com/articles/CBMiamh0dHA6Ly9ha3VyYXQuY28vZWtvbm9taS9pZC04NDc3MjEtcmVhZC1uZXRmbGl4LWRhbi1pZmxpeC1zdW1iYW5nLXBlcmxhbWJhdGFuLWVrb25vbWktcmktdHJpd3VsYW4taWlpLTIwMTnSAQA?hl=id&gl=ID&ceid=ID%3Aid', 7),
('Layanan Nonton Film Streaming Salah Satu Penyebab Perlambatan Pertumbuhan Ekonomi RI  merdeka.com', 'Merdeka.com - Badan Pusat Statistik (BPS) mencatat pertumbuhan ekonomi pada kuartal III 2019 sebesar 5,02 persen. Angka tersebut melambat jika ...', 'merdeka.com', '2019-11-07', 'http://news.google.com/articles/CBMidmh0dHBzOi8vd3d3Lm1lcmRla2EuY29tL3VhbmcvbGF5YW5hbi1ub250b24tZmlsbS1zdHJlYW1pbmctc2FsYWgtc2F0dS1wZW55ZWJhYi1wZXJsYW1iYXRhbi1wZXJ0dW1idWhhbi1la29ub21pLXJpLmh0bWzSAXhodHRwczovL20ubWVyZGVrYS5jb20vYW1wL3VhbmcvbGF5YW5hbi1ub250b24tZmlsbS1zdHJlYW1pbmctc2FsYWgtc2F0dS1wZW55ZWJhYi1wZXJsYW1iYXRhbi1wZXJ0dW1idWhhbi1la29ub21pLXJpLmh0bWw?hl=id&gl=ID&ceid=ID%3Aid', 8),
('Kepala BPS: Kami Tidak Boleh Memihak! - Kompas.com', 'Tiap BPS merilis data statistik, selalu ada pihak yang tidak suka hasilnya maupun yang menyukai hasilnya. Halaman all.', 'KOMPAS.com', '2019-11-07', 'http://news.google.com/articles/CBMiYWh0dHBzOi8vbW9uZXkua29tcGFzLmNvbS9yZWFkLzIwMTkvMTEvMDcvMTYwNzAwMjI2L2tlcGFsYS1icHMtLWthbWktdGlkYWstYm9sZWgtbWVtaWhhay0_cGFnZT1hbGzSAVxodHRwczovL2FtcC5rb21wYXMuY29tL21vbmV5L3JlYWQvMjAxOS8xMS8wNy8xNjA3MDAyMjYva2VwYWxhLWJwcy0ta2FtaS10aWRhay1ib2xlaC1tZW1paGFrLQ?hl=id&gl=ID&ceid=ID%3Aid', 9),
('Data BPS Cerminkan Ekonomi Indonesia Melemah', 'JAKARTA  Penurunan impor yang cukup dalam menunjukkan perekonomian Indonesia ke depan melambat. Pasalnya, sebagian besar barang yang diimpor ...', 'Validnews', '2019-11-07', 'http://news.google.com/articles/CBMiSWh0dHBzOi8vd3d3LnZhbGlkbmV3cy5pZC9EYXRhLUJQUy1DZXJtaW5rYW4tRWtvbm9taS1JbmRvbmVzaWEtTWVsZW1haC1oR0PSAQA?hl=id&gl=ID&ceid=ID%3Aid', 10),
('Sektor Tambang Jadi Penyelamat Ekonomi Kaltim, Pertumbuhannya di Atas Ekspektasi', 'Pertumbuhan ekonomi provinsi Kalimantan Timur diprediksikan masih tumbuh melesat hingga akhir tahun ini dibandingkan dengan tahun lalu, karena kinerja ...', 'Bisnis.com', '2019-11-07', 'http://news.google.com/articles/CBMihwFodHRwczovL2thbGltYW50YW4uYmlzbmlzLmNvbS9yZWFkLzIwMTkxMTA3LzQwOC8xMTY3OTUzL3Nla3Rvci10YW1iYW5nLWphZGktcGVueWVsYW1hdC1la29ub21pLWthbHRpbS1wZXJ0dW1idWhhbm55YS1kaS1hdGFzLWVrc3Bla3Rhc2nSAQA?hl=id&gl=ID&ceid=ID%3Aid', 11),
('Layanan Film Streaming Sumbang Perlambatan Ekonomi RI', 'Pertumbuhan ekonomi Indonesia hanya mencapai 502 year on yearyoy di kuartal III2019 - Fiskal & Moneter - okezone economy.', 'Okezone', '2019-11-07', 'http://news.google.com/articles/CBMibGh0dHBzOi8vZWNvbm9teS5va2V6b25lLmNvbS9yZWFkLzIwMTkvMTEvMDcvMjAvMjEyNjkxNy9sYXlhbmFuLWZpbG0tc3RyZWFtaW5nLXN1bWJhbmctcGVybGFtYmF0YW4tZWtvbm9taS1yadIBAA?hl=id&gl=ID&ceid=ID%3Aid', 12),
('Ekonomi RI Sedang Berat, Tengok Saja Kinerja Emiten Ritel', 'Jakarta, CNBC Indonesia - Tren perlambatan ekonomi Indonesia semakin nyata setelah Badan Pusat Statistik (BPS) menyampaikan pertumbuhan ekonomi ...', 'CNBC Indonesia', '2019-11-07', 'http://news.google.com/articles/CBMidmh0dHBzOi8vd3d3LmNuYmNpbmRvbmVzaWEuY29tL21hcmtldC8yMDE5MTEwNzEyMTE1OC0xNy0xMTMzOTkvZWtvbm9taS1yaS1zZWRhbmctYmVyYXQtdGVuZ29rLXNhamEta2luZXJqYS1lbWl0ZW4tcml0ZWzSAQA?hl=id&gl=ID&ceid=ID%3Aid', 13),
('Wah, BPS Sebut Netflix Cs Ikut Bikin Ekonomi RI Loyo', 'BPS menyebut penyebab lesunya ekonomi karena film lolos sensor di bioskop jumlahnya turun 45%.', 'CNBC Indonesia', '2019-11-07', 'http://news.google.com/articles/CBMib2h0dHBzOi8vd3d3LmNuYmNpbmRvbmVzaWEuY29tL3RlY2gvMjAxOTExMDcxMzM4MTctMzctMTEzNDQ4L3dhaC1icHMtc2VidXQtbmV0ZmxpeC1jcy1pa3V0LWJpa2luLWVrb25vbWktcmktbG95b9IBAA?hl=id&gl=ID&ceid=ID%3Aid', 14),
('BPS Bantah Adanya Manipulasi Data', 'Liputan6.com, Jakarta - Kepala Badan Pusat Statistik (BPS) Suhariyanto mengatakan, independensi merupakan landasan bagi pihaknya untuk menyajikan data ...', 'Liputan6.com', '2019-11-07', 'http://news.google.com/articles/CBMiTmh0dHBzOi8vd3d3LmxpcHV0YW42LmNvbS9iaXNuaXMvcmVhZC80MTA1MjUwL2Jwcy1iYW50YWgtYWRhbnlhLW1hbmlwdWxhc2ktZGF0YdIBRGh0dHBzOi8vbS5saXB1dGFuNi5jb20vYW1wLzQxMDUyNTAvYnBzLWJhbnRhaC1hZGFueWEtbWFuaXB1bGFzaS1kYXRh?hl=id&gl=ID&ceid=ID%3Aid', 15),
('Pertumbuhan Ekonomi Kalsel Triwulan III 2019, Sebesar 4,01 Persen', 'BANJARBARU, koranbanjar.net -Pertumbuhan Ekonomi Provinsi Kalimantan Selatan customer to costumer (c-to-c) sebesar 4,01 persen. Berdasarkan rilis ...', 'Koran Banjar', '2019-11-07', 'http://news.google.com/articles/CBMiWGh0dHBzOi8va29yYW5iYW5qYXIubmV0L3BlcnR1bWJ1aGFuLWVrb25vbWkta2Fsc2VsLXRyaXd1bGFuLWlpaS0yMDE5LXNlYmVzYXItNDAxLXBlcnNlbi_SAQA?hl=id&gl=ID&ceid=ID%3Aid', 16),
('Kepala BPS: Independensi Harga Mati  merdeka.com', 'Kepala Badan Pusat Statistik (BPS) Suhariyanto mengatakan, independensi merupakan landasan bagi pihaknya untuk menyajikan data utuh perekonomian ...', 'merdeka.com', '2019-11-07', 'http://news.google.com/articles/CBMiRGh0dHBzOi8vd3d3Lm1lcmRla2EuY29tL3Vhbmcva2VwYWxhLWJwcy1pbmRlcGVuZGVuc2ktaGFyZ2EtbWF0aS5odG1s0gFGaHR0cHM6Ly9tLm1lcmRla2EuY29tL2FtcC91YW5nL2tlcGFsYS1icHMtaW5kZXBlbmRlbnNpLWhhcmdhLW1hdGkuaHRtbA?hl=id&gl=ID&ceid=ID%3Aid', 17),
('Indeks tendensi konsumen Papua mencapai 100,08', 'menunjukan ekonomi konsumen mengalami peningkatan dengan tingkat optimisme yang lebih rendah dibandingkan triwulan sebelumnya. Papua No. 1 News ...', 'JUBI', '2019-11-07', 'http://news.google.com/articles/CBMiRWh0dHBzOi8vd3d3Lmp1YmkuY28uaWQvaW5kZWtzLXRlbmRlbnNpLWtvbnN1bWVuLXBhcHVhLW1lbmNhcGFpLTEwMDA4L9IBAA?hl=id&gl=ID&ceid=ID%3Aid', 18),
('Bos BPS Tegaskan Independensi Dalam Sajikan Data Harga Mati!', 'Sempat diragukan, Bos BPS kembali menegaskan bahwa independensi harga mati meskipun posisi BPS langsung dibawahi oleh Presiden Jokowi.', 'akurat', '2019-11-07', 'http://news.google.com/articles/CBMiZGh0dHBzOi8vYWt1cmF0LmNvL2Vrb25vbWkvaWQtODQ3MzE3LXJlYWQtYm9zLWJwcy10ZWdhc2thbi1pbmRlcGVuZGVuc2ktZGFsYW0tc2FqaWthbi1kYXRhLWhhcmdhLW1hdGnSAQA?hl=id&gl=ID&ceid=ID%3Aid', 19),
('BPS: Layanan Film Streaming Sumbang Perlambatan Ekonomi RI - kumparan.com', 'Film yang lolos sensor di Bioskop jumlahnya turun 45 persen.', 'kumparan.com', '2019-11-07', 'http://news.google.com/articles/CBMiaWh0dHBzOi8va3VtcGFyYW4uY29tL2t1bXBhcmFuYmlzbmlzL2Jwcy1sYXlhbmFuLWZpbG0tc3RyZWFtaW5nLXN1bWJhbmctcGVybGFtYmF0YW4tZWtvbm9taS1yaS0xc0NvTGpBMUo2NtIBb2h0dHBzOi8vbS5rdW1wYXJhbi5jb20vYW1wL2t1bXBhcmFuYmlzbmlzL2Jwcy1sYXlhbmFuLWZpbG0tc3RyZWFtaW5nLXN1bWJhbmctcGVybGFtYmF0YW4tZWtvbm9taS1yaS0xc0NvTGpBMUo2Ng?hl=id&gl=ID&ceid=ID%3Aid', 20),
('Dibayangi Perang Dagang, Ekonomi Indonesia Masih Tumbuh 5 Persen pada Triwulan III 2019', 'Di tengah terjadinya perang dagang antara Amerika Serikat (AS) dengan Tiongkok, ekonomi Indonesia masih tumbuh di atas 5 persen. Kondisi ini berbeda ...', 'Databoks', '2019-11-07', 'http://news.google.com/articles/CBMijQFodHRwczovL2RhdGFib2tzLmthdGFkYXRhLmNvLmlkL2RhdGFwdWJsaXNoLzIwMTkvMTEvMDcvZGliYXlhbmdpLXBlcmFuZy1kYWdhbmctZWtvbm9taS1pbmRvbmVzaWEtbWFzaWgtdHVtYnVoLTUtcGVyc2VuLXBhZGEtdHJpd3VsYW4taWlpLTIwMTnSAQA?hl=id&gl=ID&ceid=ID%3Aid', 21),
('Pertumbuhan Ekspor Rendah Picu Melambatnya Ekonomi di Sumut', 'Oleh: Anita Sinuhaji. medaninside.com, Medan- Pertumbuhan Ekonomi di Triwulan III 2019 yang mencapai 5,11 persen ternyata mengalami perlambatan.', 'MEDANINSIDE.COM', '2019-11-07', 'http://news.google.com/articles/CBMiVGh0dHBzOi8vbWVkYW5pbnNpZGUuY29tL3BlcnR1bWJ1aGFuLWVrc3Bvci1yZW5kYWgtcGljdS1tZWxhbWJhdG55YS1la29ub21pLWRpLXN1bXV0L9IBAA?hl=id&gl=ID&ceid=ID%3Aid', 22),
('Pertumbuhan Ekonomi Jambi Melambat', 'JAMBI  Pertumbuhan Ekonomi Provinsi Jambi Triwulan III tahun 2019 tumbuh sebesar 4,31 persen (y-on-y). Ini berdasarkan data yang dirilis Badan Pusat.', 'fin', '2019-11-07', 'http://news.google.com/articles/CBMiQGh0dHBzOi8vZmluLmNvLmlkLzIwMTkvMTEvMDcvcGVydHVtYnVoYW4tZWtvbm9taS1qYW1iaS1tZWxhbWJhdC_SAQA?hl=id&gl=ID&ceid=ID%3Aid', 23),
('Ekonomi RI Diragukan Tumbuh 5,02%, Kenapa?', 'JAKARTA - Pertumbuhan ekonomi Indonesia pada triwulan III-2019 yang mencapai 5,02% menimbulkan banyak spekulasi dari berbagai kalangan. Ada yang ...', 'Riau Editor', '2019-11-07', 'http://news.google.com/articles/CBMiXmh0dHBzOi8vd3d3LnJpYXVlZGl0b3IuY29tL3ZpZXcvTmFzaW9uYWwvNjIzNDYvRWtvbm9taS1SSS1EaXJhZ3VrYW4tVHVtYnVoLTUtMDItLS1LZW5hcGEtLmh0bWzSAQA?hl=id&gl=ID&ceid=ID%3Aid', 24),
('BPS Catat Pemenuhan Konsumsi Masyarakat Bali Triwulan III Turun', 'Secara umum kondisi ekonomi masyarakat Bali dalam memenuhi kebutuhan konsumsinya pada triwulan Ill 2019 dipersepsikan berada pada posisi nyaman ...', 'Tribun Bali', '2019-11-07', 'http://news.google.com/articles/CAIiELGEwvT-6Hhq-xiJIDjpq9kqGQgEKhAIACoHCAowmpWOCzD78qADMIDrqwY?hl=id&gl=ID&ceid=ID%3Aid', 25),
('Sumber Pertumbuhan Ekonomi di Sumut Masih Didorong Konsumsi Rumah Tangga', 'Indonesiainside.id, Medan- Ekonomi Sumatera Utara (Sumut) Triwulan III tercatat tumbuh 5,11 persen, di Triwulan II tumbuh 5,25 persen dan di Triwulan I ...', 'INDONESIAINSIDE.ID', '2019-11-07', 'http://news.google.com/articles/CBMigAFodHRwczovL2luZG9uZXNpYWluc2lkZS5pZC9pbmktbmV0d29yay9tZWRhbi8yMDE5LzExLzA3L3N1bWJlci1wZXJ0dW1idWhhbi1la29ub21pLWRpLXN1bXV0LW1hc2loLWRpZG9yb25nLWtvbnN1bXNpLXJ1bWFoLXRhbmdnYdIBhAFodHRwczovL2luZG9uZXNpYWluc2lkZS5pZC9pbmktbmV0d29yay9tZWRhbi8yMDE5LzExLzA3L3N1bWJlci1wZXJ0dW1idWhhbi1la29ub21pLWRpLXN1bXV0LW1hc2loLWRpZG9yb25nLWtvbnN1bXNpLXJ1bWFoLXRhbmdnYS9hbXA?hl=id&gl=ID&ceid=ID%3Aid', 26),
('Sumber Pertumbuhan Ekonomi Investasi dan Ekspor Masih Lemah di Sumut', 'MEDAN-Pertumbuhan ekonomi Sumatera Utara (Sumut) pada Triwulan III tercatat tumbuh 5,11 persen di Triwulan II tumbuh 5,25 persen dan di Triwulan I ...', 'GoSumut', '2019-11-07', 'http://news.google.com/articles/CBMicWh0dHBzOi8vbS5nb3N1bXV0LmNvbS9iZXJpdGEvYmFjYS8yMDE5LzExLzA3L3N1bWJlci1wZXJ0dW1idWhhbi1la29ub21pLWludmVzdGFzaS1kYW4tZWtzcG9yLW1hc2loLWxlbWFoLWRpLXN1bXV00gEA?hl=id&gl=ID&ceid=ID%3Aid', 27),
('Pertumbuhan Ekonomi NTT Triwulan III-2019 Sebesar 3,87 Persen', 'Kupang, fokusnusatenggara.com / 6 November 2019. Perekonomian Nusa Tenggara Timur (NTT) berdasarkan besaran Produk Domestik Bruto (PDRB) atas ...', 'FOKUS NUSA TENGGARA', '2019-11-07', 'http://news.google.com/articles/CBMiamh0dHBzOi8vd3d3LmZva3VzbnVzYXRlbmdnYXJhLmNvbS9saW50YXMtbnR0L3BlcnR1bWJ1aGFuLWVrb25vbWktbnR0LXRyaXd1bGFuLWlpaS0yMDE5LXNlYmVzYXItMzg3LXBlcnNlbi_SAQA?hl=id&gl=ID&ceid=ID%3Aid', 28),
('Ekonomi Bali Melambat, Triwulan III-2019 Tak Sebaik 2018', 'Triwulan III, perekonomian Bali tumbuh, tapi tak sebaik pertumbuhan pada periode yang sama tahun lalu.', 'NusaBali', '2019-11-06', 'http://news.google.com/articles/CBMiXWh0dHBzOi8vd3d3Lm51c2FiYWxpLmNvbS9iZXJpdGEvNjI3OTgvZWtvbm9taS1iYWxpLW1lbGFtYmF0LXRyaXd1bGFuLWlpaS0yMDE5LXRhay1zZWJhaWstMjAxONIBAA?hl=id&gl=ID&ceid=ID%3Aid', 29),
('BPS Jatim: Indeks Tendensi Konsumen Turun Jadi 99,44', 'SU - Badan Pusat Statistik (BPS) Jawa Timur (Jatim) mencatat, Indeks Tendensi Konsumen (ITK) Jatim pada Triwulan III 2019 sebesar 99,44 atau di bawah 100.', 'SINDOnews.com', '2019-11-06', 'http://news.google.com/articles/CBMiZmh0dHBzOi8vamF0aW0uc2luZG9uZXdzLmNvbS9yZWFkLzE2MTg4LzEvYnBzLWphdGltLWluZGVrcy10ZW5kZW5zaS1rb25zdW1lbi10dXJ1bi1qYWRpLTk5NDQtMTU3MzA4MTg5NNIBamh0dHBzOi8vamF0aW0uc2luZG9uZXdzLmNvbS9uZXdzcmVhZC8xNjE4OC8xL2Jwcy1qYXRpbS1pbmRla3MtdGVuZGVuc2kta29uc3VtZW4tdHVydW4tamFkaS05OTQ0LTE1NzMwODE4OTQ?hl=id&gl=ID&ceid=ID%3Aid', 30),
('Pertumbuhan Ekonomi Papua Triwulan III  2019 Turun  15,11 Persen', 'Koreri.com, Jayapura  Pertumbuhan ekonomi Papua triwulan III  2019 mengalami kontraksi sebesar -15,11 persen (y on y). Kepala Bidang Nerwilis BPS ...', 'Koreri', '2019-11-06', 'http://news.google.com/articles/CBMiXGh0dHBzOi8va29yZXJpLmNvbS8yMDE5LzExLzA3L3BlcnR1bWJ1aGFuLWVrb25vbWktcGFwdWEtdHJpd3VsYW4taWlpLTIwMTktdHVydW4tMTUxMS1wZXJzZW4v0gFgaHR0cHM6Ly9rb3JlcmkuY29tLzIwMTkvMTEvMDcvcGVydHVtYnVoYW4tZWtvbm9taS1wYXB1YS10cml3dWxhbi1paWktMjAxOS10dXJ1bi0xNTExLXBlcnNlbi9hbXAv?hl=id&gl=ID&ceid=ID%3Aid', 31),
('Pendapatan & Perubahan Harga Pengaruhi Tingkat Konsumsi', 'Kondisi ekonomi konsumen rumah tangga di DIY selama triwulan III2019 berada pada taraf optimistis atau lebih baik Hal ini terlihat dari nilai Indeks Tendensi ...', 'Harian Jogja', '2019-11-06', 'http://news.google.com/articles/CBMib2h0dHBzOi8vZWtiaXMuaGFyaWFuam9namEuY29tL3JlYWQvMjAxOS8xMS8wNi81MDIvMTAyNDExNS9wZW5kYXBhdGFuLXBlcnViYWhhbi1oYXJnYS1wZW5nYXJ1aGktdGluZ2thdC1rb25zdW1zadIBAA?hl=id&gl=ID&ceid=ID%3Aid', 32),
('Pada triwulan ketiga Indeks tendensi konsumen Papua capai 100,08', 'Badan Pusat Statistik (BPS) Provinsi Papua menyatakan Indeks Tendensi Konsumen (ITK) setempat mencapai 100,08 pada triwulan ketiga 2019, yang berarti ...', 'Antara Banten', '2019-11-06', 'http://news.google.com/articles/CBMiamh0dHBzOi8vYmFudGVuLmFudGFyYW5ld3MuY29tL2Jlcml0YS83MTM4NC9wYWRhLXRyaXd1bGFuLWtldGlnYS1pbmRla3MtdGVuZGVuc2kta29uc3VtZW4tcGFwdWEtY2FwYWktMTAwMDjSAW5odHRwczovL2JhbnRlbi5hbnRhcmFuZXdzLmNvbS9hbXAvYmVyaXRhLzcxMzg0L3BhZGEtdHJpd3VsYW4ta2V0aWdhLWluZGVrcy10ZW5kZW5zaS1rb25zdW1lbi1wYXB1YS1jYXBhaS0xMDAwOA?hl=id&gl=ID&ceid=ID%3Aid', 33),
('Perang Dagang Tekan Pertumbuhan', 'JawaPos.com  Ketidakpastian global memukul perekonomian negara-negara di dunia. Tidak terkecuali Indonesia. Hal itu tecermin dari capaian pertumbuhan ...', 'Jawa Pos', '2019-11-06', 'http://news.google.com/articles/CBMiS2h0dHBzOi8vd3d3Lmphd2Fwb3MuY29tL2Vrb25vbWkvMDYvMTEvMjAxOS9wZXJhbmctZGFnYW5nLXRla2FuLXBlcnR1bWJ1aGFuL9IBT2h0dHBzOi8vd3d3Lmphd2Fwb3MuY29tL2Vrb25vbWkvMDYvMTEvMjAxOS9wZXJhbmctZGFnYW5nLXRla2FuLXBlcnR1bWJ1aGFuLz9hbXA?hl=id&gl=ID&ceid=ID%3Aid', 34),
('6 Bulan Ke Depan, Daya Beli Diperkirakan Masih Lemah', 'Survei Penjualan Eceran September 2019 dari Bank Indonesia menyatakan penjualan eceran tumbuh melambat. Pasalnya, Indeks Penjualan Riil (IPR) ...', 'Bisnis.com', '2019-11-06', 'http://news.google.com/articles/CBMiZmh0dHBzOi8vZWtvbm9taS5iaXNuaXMuY29tL3JlYWQvMjAxOTExMDYvOS8xMTY3NTc2LzYtYnVsYW4ta2UtZGVwYW4tZGF5YS1iZWxpLWRpcGVya2lyYWthbi1tYXNpaC1sZW1haNIBZGh0dHBzOi8vbS5iaXNuaXMuY29tL2FtcC9yZWFkLzIwMTkxMTA2LzkvMTE2NzU3Ni82LWJ1bGFuLWtlLWRlcGFuLWRheWEtYmVsaS1kaXBlcmtpcmFrYW4tbWFzaWgtbGVtYWg?hl=id&gl=ID&ceid=ID%3Aid', 35),
('Masyarakat Anggap Kondisi Ekonomi Konsumen Tak Lebih Baik Dari Sebelumnya', 'BANJARBARU, koranbanjar.net  Indeks Tendensi Konsumen (ITK) Kalimantan Selatan (Kalsel) pada triwulan III 2019 sebesar 99,51. Hal tersebut ...', 'Koran Banjar', '2019-11-06', 'http://news.google.com/articles/CBMiYmh0dHBzOi8va29yYW5iYW5qYXIubmV0L21hc3lhcmFrYXQtYW5nZ2FwLWtvbmRpc2ktZWtvbm9taS1rb25zdW1lbi10YWstbGViaWgtYmFpay1kYXJpLXNlYmVsdW1ueWEv0gEA?hl=id&gl=ID&ceid=ID%3Aid', 36),
('Ekonomi Papua Triwulan III 2019 Turun 15,11 Persen  Berita Terbaru - Harian Ekonomi & Bisnis di Papua - www.bisnis-papua.com - saatnya berpikir ekonomi.', 'Kepala Bidang Nerwilis BPS provinsi papua, Eko Mardiana, menyampaikan berita resmi statistic, Selasa ( 5/11/2019).- ( Muhammad Kasim /BP ).', 'Bisnis Papua', '2019-11-06', 'http://news.google.com/articles/CBMiT2h0dHBzOi8vd3d3LmJpc25pcy1wYXB1YS5jb20vZWtvbm9taS1wYXB1YS10cml3dWxhbi1paWktMjAxOS10dXJ1bi0xNTExLXBlcnNlbi_SAQA?hl=id&gl=ID&ceid=ID%3Aid', 37),
('BPS: Triwulan III-2019, Ekonomi Indonesia Tumbuh 5,02 Persen', 'JAKARTA.NIAGA.ASIA-Badan Pusat Statistik (BPS) menginformasikan, bahwa ekonomi Indonesia triwulan III-2019 dibanding triwulan III-2018 (y-on-y) tumbuh ...', 'Niaga Asia', '2019-11-06', 'http://news.google.com/articles/CBMiUWh0dHBzOi8vd3d3Lm5pYWdhLmFzaWEvYnBzLXRyaXd1bGFuLWlpaS0yMDE5LWVrb25vbWktaW5kb25lc2lhLXR1bWJ1aC01MDItcGVyc2VuL9IBAA?hl=id&gl=ID&ceid=ID%3Aid', 38),
('BPS : Triwulan III-2019, Ekonomi Indonesia Tumbuh 5,02 Persen', 'kabarSBI.com  Badan Pusat Statistik (BPS) menginformasikan, bahwa ekonomi Indonesia triwulan III-2019 dibanding triwulan III-2018 (y-on-y) tumbuh 5,02 ...', 'Kabar SBI', '2019-11-06', 'http://news.google.com/articles/CBMiT2h0dHBzOi8va2FiYXJzYmkuY29tL2Jwcy10cml3dWxhbi1paWktMjAxOS1la29ub21pLWluZG9uZXNpYS10dW1idWgtNTAyLXBlcnNlbi_SAQA?hl=id&gl=ID&ceid=ID%3Aid', 39),
('Perang Dagang Tekan Pertumbuhan, Iklim Bisnis Terdampak', 'PROKAL.CO, JAKARTA Ketidakpastian global memukul perekonomian negara-negara di dunia. Tidak terkecuali Indonesia. Hal itu tecermin dari capaian ...', 'Kaltim Post', '2019-11-06', 'http://news.google.com/articles/CBMiYGh0dHBzOi8va2FsdGltLnByb2thbC5jby9yZWFkL25ld3MvMzYzMjA3LXBlcmFuZy1kYWdhbmctdGVrYW4tcGVydHVtYnVoYW4taWtsaW0tYmlzbmlzLXRlcmRhbXBha9IBAA?hl=id&gl=ID&ceid=ID%3Aid', 40),
('Indeks Tendensi Konsumen Lampung Naik', 'Badan Pusat Statistik (BPS) Provinsi Lampung mencatat Indeks Tendesi Konsumen (ITK) di bumi Rua Jurai membaik. Menurut BPS, ITK Lampung triwulan III ...', 'Lampost', '2019-11-06', 'http://news.google.com/articles/CBMiSGh0dHBzOi8vd3d3LmxhbXBvc3QuY28vYmVyaXRhLWluZGVrcy10ZW5kZW5zaS1rb25zdW1lbi1sYW1wdW5nLW5haWsuaHRtbNIBRWh0dHBzOi8vd3d3LmxhbXBvc3QuY28vYW1wL2luZGVrcy10ZW5kZW5zaS1rb25zdW1lbi1sYW1wdW5nLW5haWsuaHRtbA?hl=id&gl=ID&ceid=ID%3Aid', 41),
('Ekonomi Kuartal III Melempem, Rakyat RI Optimis di Kuartal IV Pulih', 'Badan Pusat Statistik (BPS) mencatat indeks tendensi konsumen (ITK) nasional pada kuartal III 2019 mengalami penurunan menjadi 101,03 dibanding kuartal ...', 'Investing.com Indonesia', '2019-11-06', 'http://news.google.com/articles/CBMicGh0dHBzOi8vaWQuaW52ZXN0aW5nLmNvbS9uZXdzL2Vjb25vbXkvZWtvbm9taS1rdWFydGFsLWlpaS1tZWxlbXBlbS1yYWt5YXQtcmktb3B0aW1pcy1kaS1rdWFydGFsLWl2LXB1bGloLTE5MzI1ODnSAQA?hl=id&gl=ID&ceid=ID%3Aid', 42),
('Ekonomi Riau Triwulan III Melambat Dibandingkan Periode Tahun Lalu', 'Walau BPS Provinsi Riau mencatat ekonomi Provinsi Riau triwulan III 2019 tumbuh 2,74 persen, namun faktanya ekonomi Riau melambat.', 'Kitakini News', '2019-11-06', 'http://news.google.com/articles/CBMiamh0dHBzOi8va2l0YWtpbmkubmV3cy80MzM4MS9la29ub21pLXJpYXUtdHJpd3VsYW4taWlpLW1lbGFtYmF0LWRpYmFuZGluZ2thbi10cml3dWxhbi15YW5nLXNhbWEtdGFodW4tbGFsdS_SAW5odHRwczovL2tpdGFraW5pLm5ld3MvNDMzODEvZWtvbm9taS1yaWF1LXRyaXd1bGFuLWlpaS1tZWxhbWJhdC1kaWJhbmRpbmdrYW4tdHJpd3VsYW4teWFuZy1zYW1hLXRhaHVuLWxhbHUvP2FtcA?hl=id&gl=ID&ceid=ID%3Aid', 43),
('Ekonomi Jatim di Triwulan III 2019 Tumbuh 5,32 Persen, Sumbangan Terbesar dari Jasa Pendidikan', 'Ekonomi Jatim di Triwulan III 2019 Tumbuh 5,32 Persen, Sumbangan Terbesar dari Jasa Pendidikan.', 'TribunJatim.com', '2019-11-06', 'http://news.google.com/articles/CAIiEKcH6qmO_EOCJKFIuZvJZ38qGQgEKhAIACoHCAows5-OCzDRiqEDMMjaqwY?hl=id&gl=ID&ceid=ID%3Aid', 44),
('ITK Sulawesi Utara triwulan III-2019 tertinggi di Sulampua', 'Manado (ANTARA) - Indeks Tendensi Konsumen (ITK) Sulawesi Utara (Sulut) triwulan III tahun 2019 merupakan tertinggi di wilayah Sulawesi, Maluku dan ...', 'ANTARA', '2019-11-06', 'http://news.google.com/articles/CBMiZGh0dHBzOi8vd3d3LmFudGFyYW5ld3MuY29tL2Jlcml0YS8xMTQ5NDQ0L2l0ay1zdWxhd2VzaS11dGFyYS10cml3dWxhbi1paWktMjAxOS10ZXJ0aW5nZ2ktZGktc3VsYW1wdWHSAWZodHRwczovL20uYW50YXJhbmV3cy5jb20vYW1wL2Jlcml0YS8xMTQ5NDQ0L2l0ay1zdWxhd2VzaS11dGFyYS10cml3dWxhbi1paWktMjAxOS10ZXJ0aW5nZ2ktZGktc3VsYW1wdWE?hl=id&gl=ID&ceid=ID%3Aid', 45),
('BPS: Triwulan III-2019, Ekonomi Indonesia Tumbuh 5,02%', 'Jakarta, Nusantaratv.com - Badan Pusat Statistik (BPS) menginformasikan, bahwa ekonomi Indonesia triwulan III-2019 dibanding triwulan III-2018 tumbuh 5 ...', 'Nusantaratv.com', '2019-11-06', 'http://news.google.com/articles/CBMiU2h0dHBzOi8vbnVzYW50YXJhdHYuY29tL2tldWFuZ2FuL2Jwcy10cml3dWxhbi1paWktMjAxOS1la29ub21pLWluZG9uZXNpYS10dW1idWgtNTAy0gEA?hl=id&gl=ID&ceid=ID%3Aid', 46),
('BPS Sulsel: Masyarakat Masih Optimis Hadapi Perekonomian', 'Kepala BPS Sulsel, Yos Rusdiansyah menjelaskan, Indeks Tendensi Konsumen (ITK) Sulsel pada Triwulan III-2019 sebesar 104,18, artinya kondisi ekonomi.', 'Tribun Timur', '2019-11-06', 'http://news.google.com/articles/CBMiYmh0dHBzOi8vbWFrYXNzYXIudHJpYnVubmV3cy5jb20vMjAxOS8xMS8wNi9icHMtc3Vsc2VsLW1hc3lhcmFrYXQtbWFzaWgtb3B0aW1pcy1oYWRhcGktcGVyZWtvbm9taWFu0gFmaHR0cHM6Ly9tYWthc3Nhci50cmlidW5uZXdzLmNvbS9hbXAvMjAxOS8xMS8wNi9icHMtc3Vsc2VsLW1hc3lhcmFrYXQtbWFzaWgtb3B0aW1pcy1oYWRhcGktcGVyZWtvbm9taWFu?hl=id&gl=ID&ceid=ID%3Aid', 47),
('Investasi Sentuh Titik Terendah dalam Dua Tahun Terakhir', 'Seluruh komponen PMTB dalam periode triwulan III-2019 seperti bangunan, mesin dan perlengkapan, kendaraan, peralatan lainnya, CBR dan produk ...', 'INDONESIAINSIDE.ID', '2019-11-06', 'http://news.google.com/articles/CBMiZmh0dHBzOi8vaW5kb25lc2lhaW5zaWRlLmlkL2Vrb25vbWkvMjAxOS8xMS8wNi9pbnZlc3Rhc2ktc2VudHVoLXRpdGlrLXRlcmVuZGFoLWRhbGFtLWR1YS10YWh1bi10ZXJha2hpctIBamh0dHBzOi8vaW5kb25lc2lhaW5zaWRlLmlkL2Vrb25vbWkvMjAxOS8xMS8wNi9pbnZlc3Rhc2ktc2VudHVoLXRpdGlrLXRlcmVuZGFoLWRhbGFtLWR1YS10YWh1bi10ZXJha2hpci9hbXA?hl=id&gl=ID&ceid=ID%3Aid', 48),
('ITK Papua 100,08, BPS : Kondisi Ekonomi Konsumen Meningkat', 'Beri rating artikel ini. 1', 'Pasific Pos.com', '2019-11-06', 'http://news.google.com/articles/CBMiXWh0dHBzOi8vd3d3LnBhc2lmaWNwb3MuY29tL2l0ZW0vMzc3NjAtaXRrLXBhcHVhLTEwMC0wOC1icHMta29uZGlzaS1la29ub21pLWtvbnN1bWVuLW1lbmluZ2thdNIBAA?hl=id&gl=ID&ceid=ID%3Aid', 49),
('VIDEO: Ekonomi Sulsel Triwulan III Tumbuh 7,21 Persen', 'VIDEO: Ekonomi Sulsel Triwulan III Tumbuh 7,21 Persen. BPS Sulawesi Selatan (Sulsel) merilis pertumbuhan ekonomi Sulsel pada triwulan III 2019.', 'Tribun Timur', '2019-11-06', 'http://news.google.com/articles/CBMiXmh0dHBzOi8vbWFrYXNzYXIudHJpYnVubmV3cy5jb20vMjAxOS8xMS8wNi92aWRlby1la29ub21pLXN1bHNlbC10cml3dWxhbi1paWktdHVtYnVoLTcyMS1wZXJzZW7SAWJodHRwczovL21ha2Fzc2FyLnRyaWJ1bm5ld3MuY29tL2FtcC8yMDE5LzExLzA2L3ZpZGVvLWVrb25vbWktc3Vsc2VsLXRyaXd1bGFuLWlpaS10dW1idWgtNzIxLXBlcnNlbg?hl=id&gl=ID&ceid=ID%3Aid', 50),
('Sstt.. Ada yang Tak Percaya PDB RI Tumbuh 5,02%', 'Pertumbuhan ekonomi Indonesia pada triwulan III-2019 yang mencapai 5,02% menimbulkan banyak spekulasi dari berbagai kalangan.', 'CNBC Indonesia', '2019-11-06', 'http://news.google.com/articles/CBMiZmh0dHBzOi8vd3d3LmNuYmNpbmRvbmVzaWEuY29tL25ld3MvMjAxOTExMDYwNzAyMDctNC0xMTI5NjUvc3N0dC1hZGEteWFuZy10YWstcGVyY2F5YS1wZGItcmktdHVtYnVoLTUwMtIBAA?hl=id&gl=ID&ceid=ID%3Aid', 51),
('Triwulan III 2019, Ekonomi Sulsel Tumbuh 7,21 Persen', 'Pedoman Rakyat, Makassar  Perekonomian Sulsel berdasarkan besaran Produk Domestik Regional Bruto (PDRB) atas dasar harga berlaku triwulan III-2019 ...', 'pedomanrakyat', '2019-11-05', 'http://news.google.com/articles/CBMiVmh0dHBzOi8vcGVkb21hbnJha3lhdC5jb20vcmVhZC81MjkvdHJpd3VsYW4taWlpLTIwMTktZWtvbm9taS1zdWxzZWwtdHVtYnVoLTcyMS1wZXJzZW4v0gEA?hl=id&gl=ID&ceid=ID%3Aid', 52),
('BPS: Triwulan III, Ekonomi Riau Tumbuh 2,74 Persen', 'PEKANBARU (RIAUSKY.COM) - Perekonomian Riau triwulan III-2019 yang diukur berdasarkan Produk Domestik Regional Bruto (PDRB) atas dasar harga ...', 'RiauSky', '2019-11-05', 'http://news.google.com/articles/CBMiWmh0dHBzOi8vcmlhdXNreS5jb20vbmV3cy9kZXRhaWwvNDM5MTEvYnBzLXRyaXd1bGFuLWlpaS1la29ub21pLXJpYXUtdHVtYnVoLTI3NC1wZXJzZW4uaHRtbNIBAA?hl=id&gl=ID&ceid=ID%3Aid', 53),
('Ekonomi Riau Tumbuh 2,74 Persen', 'HARIANRIAU.CO - Perekonomian Riau triwulan III-2019 yang diukur berdasarkan Produk Domestik Regional Bruto (PDRB) atas dasar harga berlaku mencapai ...', 'Harian Riau', '2019-11-05', 'http://news.google.com/articles/CBMiRmh0dHBzOi8vaGFyaWFucmlhdS5jby9uZXdzL2RldGFpbC8zODkzMC9la29ub21pLXJpYXUtdHVtYnVoLTI3NC1wZXJzZW7SAQA?hl=id&gl=ID&ceid=ID%3Aid', 54),
('EKONOMI : BPS: Perlambatan Realisasi Investasi Agak Dalam', 'Badan Pusat Statistik (BPS) mencatat pembentukan modal tetap bruto (PMTB) atau investasi mengalami perlambatan pada triwulan III-2019 atau hanya tumbuh ...', 'Harian Terbit', '2019-11-05', 'http://news.google.com/articles/CBMiV2h0dHBzOi8vd3d3LmhhcmlhbnRlcmJpdC5jb20vcmVhZC8xMTI3MDkvQlBTLVBlcmxhbWJhdGFuLVJlYWxpc2FzaS1JbnZlc3Rhc2ktQWdhay1EYWxhbdIBAA?hl=id&gl=ID&ceid=ID%3Aid', 55),
('BPS: Perlambatan Realisasi Investasi Agak Dalam', 'Jakarta, HanTer - Badan Pusat Statistik (BPS) mencatat pembentukan modal tetap bruto (PMTB) atau investasi mengalami perlambatan pada triwulan III-2019 ...', 'Harian Terbit', '2019-11-05', 'http://news.google.com/articles/CBMiVWh0dHBzOi8vbS5oYXJpYW50ZXJiaXQuY29tL3JlYWQvMTEyNzA5L0JQUy1QZXJsYW1iYXRhbi1SZWFsaXNhc2ktSW52ZXN0YXNpLUFnYWstRGFsYW3SAQA?hl=id&gl=ID&ceid=ID%3Aid', 56),
('Kredibilitas Data Pertumbuhan Ekonomi Diragukan, Begini Kata Kepala BPS', 'Kepala BPS Suhariyanto menanggapi kredibilitas data pertumbuhan ekonomi yang diragukan sejumlah pihak.', 'iNews', '2019-11-05', 'http://news.google.com/articles/CBMiaWh0dHBzOi8vd3d3LmluZXdzLmlkL2ZpbmFuY2UvbWFrcm8va3JlZGliaWxpdGFzLWRhdGEtcGVydHVtYnVoYW4tZWtvbm9taS1kaXJhZ3VrYW4tYmVnaW5pLWthdGEta2VwYWxhLWJwc9IBbWh0dHBzOi8vd3d3LmluZXdzLmlkL2FtcC9maW5hbmNlL21ha3JvL2tyZWRpYmlsaXRhcy1kYXRhLXBlcnR1bWJ1aGFuLWVrb25vbWktZGlyYWd1a2FuLWJlZ2luaS1rYXRhLWtlcGFsYS1icHM?hl=id&gl=ID&ceid=ID%3Aid', 57),
('Konsumen di Jateng Lebih Optimis pada Kuartal IV/2019', 'Indeks Tendensi Konsumen (ITK) diperkirakan membaik pada kuartal IV/2019 ke level 101,47, setelah menurun pada kuartal III/2019 ke level 99,48.', 'Bisnis.com', '2019-11-05', 'http://news.google.com/articles/CBMiamh0dHBzOi8vc2VtYXJhbmcuYmlzbmlzLmNvbS9yZWFkLzIwMTkxMTA1LzUzNi8xMTY3Mjc1L2tvbnN1bWVuLWRpLWphdGVuZy1sZWJpaC1vcHRpbWlzLXBhZGEta3VhcnRhbC1pdjIwMTnSAQA?hl=id&gl=ID&ceid=ID%3Aid', 58),
('Ekonomi Bengkulu Triwulan III-2019 Tumbuh 4,95 Persen', 'Bengkulutoday.com - Perekonomian Provinsi Bengkulu Triwulan III-2019 yang diukur be.', 'Bengkulu Today', '2019-11-05', 'http://news.google.com/articles/CBMiTmh0dHBzOi8vYmVuZ2t1bHV0b2RheS5jb20vZWtvbm9taS1iZW5na3VsdS10cml3dWxhbi1paWktMjAxOS10dW1idWgtNDk1LXBlcnNlbtIBAA?hl=id&gl=ID&ceid=ID%3Aid', 59),
('Ekonomi Gorontalo Tumbuh 5,67% Triwulan III Tahun 2019', 'Badan Pusat Statistik (BPS) mencatat ekonomi Gorontalo tumbuh 5,67% pada Triwulan III Tahun 2019, lebih baik jika dibandingkan Triwulan III Tahun 2018 ...', 'Hulondalo.id', '2019-11-05', 'http://news.google.com/articles/CBMiSmh0dHBzOi8vaHVsb25kYWxvLmlkL2Vrb25vbWktZ29yb250YWxvLXR1bWJ1aC01NjctdHJpd3VsYW4taWlpLXRhaHVuLTIwMTkv0gEA?hl=id&gl=ID&ceid=ID%3Aid', 60),
('Pertumbuhan Ekonomi Indonesia Triwulan III-2019', 'Foto udara lansekap kota Jakarta dilihat dari kawasan Senayan, Selasa (5/11/2019). Berdasarkan data Badan Pusat Statistik (BPS) pertumbuhan ekonomi ...', 'kompas.id', '2019-11-05', 'http://news.google.com/articles/CBMiWWh0dHBzOi8va29tcGFzLmlkL2JhY2EvZWtvbm9taS8yMDE5LzExLzA1L3BlcnR1bWJ1aGFuLWVrb25vbWktaW5kb25lc2lhLXRyaXd1bGFuLWlpaS0yMDE50gEA?hl=id&gl=ID&ceid=ID%3Aid', 61),
('Kenaikan Usaha Jasa Dorong Ekonomi RI Tumbuh 5,02 Persen', 'Kastara.ID, Jakarta  Perekonomian Indonesia tumbuh 5,02 persen pada triwulan III 2019 dibandingan periode yang sama 2018, menepis perkiraan ...', 'Kastara.ID', '2019-11-05', 'http://news.google.com/articles/CBMiVmh0dHBzOi8va2FzdGFyYS5pZC8wNS8xMS8yMDE5L2tlbmFpa2FuLXVzYWhhLWphc2EtZG9yb25nLWVrb25vbWktcmktdHVtYnVoLTUwMi1wZXJzZW4v0gFaaHR0cHM6Ly9rYXN0YXJhLmlkLzA1LzExLzIwMTkva2VuYWlrYW4tdXNhaGEtamFzYS1kb3JvbmctZWtvbm9taS1yaS10dW1idWgtNTAyLXBlcnNlbi9hbXAv?hl=id&gl=ID&ceid=ID%3Aid', 62),
('Data Pertumbuhan Ekonomi RI Diragukan, Kepala BPS Buka Suara', 'Data itu diragukan oleh beberapa ekonom asing. Salah satunya lembaga ekonomi yang bernama Capital Economics.', 'Detikcom', '2019-11-05', 'http://news.google.com/articles/CBMidWh0dHBzOi8vZmluYW5jZS5kZXRpay5jb20vYmVyaXRhLWVrb25vbWktYmlzbmlzL2QtNDc3MzE0Ni9kYXRhLXBlcnR1bWJ1aGFuLWVrb25vbWktcmktZGlyYWd1a2FuLWtlcGFsYS1icHMtYnVrYS1zdWFyYdIBAA?hl=id&gl=ID&ceid=ID%3Aid', 63),
('Triwulan III 2019, Ekonomi Sulawesi Selatan Tumbuh 7,21%', 'Badan Pusat Statistik (BPS) Sulawesi Selatan merilis pertumbuhan ekonomi provinsi ini pada triwulan III 2019 mengalami kenaikan...', 'SINDOnews.com', '2019-11-05', 'http://news.google.com/articles/CBMibGh0dHBzOi8vbWFrYXNzYXIuc2luZG9uZXdzLmNvbS9yZWFkLzM0MTY0LzMvdHJpd3VsYW4taWlpLTIwMTktZWtvbm9taS1zdWxhd2VzaS1zZWxhdGFuLXR1bWJ1aC03MjEtMTU3Mjk1MjI4NdIBcGh0dHBzOi8vbWFrYXNzYXIuc2luZG9uZXdzLmNvbS9uZXdzcmVhZC8zNDE2NC8zL3RyaXd1bGFuLWlpaS0yMDE5LWVrb25vbWktc3VsYXdlc2ktc2VsYXRhbi10dW1idWgtNzIxLTE1NzI5NTIyODU?hl=id&gl=ID&ceid=ID%3Aid', 64),
('Ekonomi Indonesia Melambat, Rupiah Justru Berakhir Naik', 'Setelah bergerak dalam kisaran yang relatif sempit, rupiah ternyata mampu bangkit ke teritori hijau pada perdagangan Selasa (5/11) sore, ketika pertumbuhan ...', 'KursRupiah.net', '2019-11-05', 'http://news.google.com/articles/CBMiQ2h0dHBzOi8va3Vyc3J1cGlhaC5uZXQvZWtvbm9taS1tZWxhbWJhdC1ydXBpYWgtYmVyYWtoaXItbmFpay8yMzMxNC_SAQA?hl=id&gl=ID&ceid=ID%3Aid', 65),
('Duh! Sektor Pertanian RI Masih Melambat, Pangan Terpuruk', 'Jakarta, CNBC Indonesia - Perlambatan ekonomi pada triwulan III-2019 juga tercermin pada sektor pertanian. Pada triwulan III-2019 total pertumbuhan ...', 'CNBC Indonesia', '2019-11-05', 'http://news.google.com/articles/CBMicWh0dHBzOi8vd3d3LmNuYmNpbmRvbmVzaWEuY29tL25ld3MvMjAxOTExMDUxNjA3MzYtNC0xMTI4NTcvZHVoLXNla3Rvci1wZXJ0YW5pYW4tcmktbWFzaWgtbWVsYW1iYXQtcGFuZ2FuLXRlcnB1cnVr0gEA?hl=id&gl=ID&ceid=ID%3Aid', 66),
('Pertumbuhan Investasi Kuartal III Anjlok, Penyebabnya Kondisi Politik?', 'BPS mencatat PMTB atau investasi pada kuartal III 2019 hanya tumbuh 4,21%, melambat dibanding kuartal III 2018 sebesar 6,96%.', 'Katadata News', '2019-11-05', 'http://news.google.com/articles/CBMibWh0dHBzOi8va2F0YWRhdGEuY28uaWQvYmVyaXRhLzIwMTkvMTEvMDUvcGVydHVtYnVoYW4taW52ZXN0YXNpLWt1YXJ0YWwtaWlpLWFuamxvay1wZW55ZWJhYm55YS1rb25kaXNpLXBvbGl0aWvSAXFodHRwczovL2FtcC5rYXRhZGF0YS5jby5pZC9iZXJpdGEvMjAxOS8xMS8wNS9wZXJ0dW1idWhhbi1pbnZlc3Rhc2kta3VhcnRhbC1paWktYW5qbG9rLXBlbnllYmFibnlhLWtvbmRpc2ktcG9saXRpaw?hl=id&gl=ID&ceid=ID%3Aid', 67),
('Ekonomi Sulsel Tumbuh 7,2%, Ini Faktor Pemicunya', 'BPS mencatat pertumbuhan Sulawesi Selatan triwulan III-2019 mencapai 7,21%. Capaian ini ditopang sektor.', 'Detikcom', '2019-11-05', 'http://news.google.com/articles/CBMiaGh0dHBzOi8vZmluYW5jZS5kZXRpay5jb20vYmVyaXRhLWVrb25vbWktYmlzbmlzL2QtNDc3Mjg1Ni9la29ub21pLXN1bHNlc2wtdHVtYnVoLTcyLWluaS1mYWt0b3ItcGVtaWN1bnlh0gEA?hl=id&gl=ID&ceid=ID%3Aid', 68),
('Ekonomi Indonesia triwulan III 2019 tumbuh 5,02 persen', 'Badan Pusat Statistik (BPS) mencatat perekonomian Indonesia pada triwulan III tahun 2019 tumbuh 5,02 persen (year on year), kata Kepala BPS Suhariyanto ...', 'Elshinta.com', '2019-11-05', 'http://news.google.com/articles/CBMiZWh0dHBzOi8vd3d3LmVsc2hpbnRhLmNvbS9uZXdzLzE5MTkwNi8yMDE5LzExLzA1L2Vrb25vbWktaW5kb25lc2lhLXRyaXd1bGFuLWlpaS0yMDE5LXR1bWJ1aC01MDItcGVyc2Vu0gEA?hl=id&gl=ID&ceid=ID%3Aid', 69);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `firstname` varchar(50) NOT NULL,
  `lastname` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(2048) NOT NULL,
  `token` varchar(1024) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `firstname`, `lastname`, `email`, `password`, `token`) VALUES
(1, 'Asmawi', 'Tri Prabowo', 'awie.net@gmail.com', '$2y$10$xpvPf6Zj.f0CJQFBVwahmOGI/T/zsFBKFsMEmoWruFmg9JNSsxF4W', '70a5c9468eef8841f310529ed056e431');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `berita`
--
ALTER TABLE `berita`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `berita`
--
ALTER TABLE `berita`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=70;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
